config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'

  resources :sessions, only: [:new, :create, :destroy]
  resources :statistics, :orders, only: [:index]

  get '/get' => 'orders#create'
  get '/cancel/:id' => 'orders#cancel'
  get '/pay/:id' => 'orders#pay'
  get '/print/:id' => 'orders#print'
  get '/web' => 'orders#web'

  get '/factory' => 'factory#index'
  get '/ready/:id' => 'factory#ready'
  get '/extradition/:id' => 'factory#extradition'
  get '/print_on_factory/:id' => 'factory#print'

  match 'test', to: 'order#testpost', via: :post

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #before_action :user_signed_in?
  helper_method :current_user
  helper_method :current_user_id

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def current_user_id
    @current_user ||= User.find_by(id: session[:user_id])
    case @current_user.role
      when 'admin'
        @current_user_id = 1
      when 'shop'
        @current_user_id = 2
      when 'showroom'
        @current_user_id = 3
      when 'elit'
        @current_user_id = 4
      else
        @current_user_id = 0
    end
  end

  def user_signed_in?
    return if current_user
    redirect_to new_session_path, notice: "Пожалуйста, пройдите авторизацию!"
  end

end

app/controllers/factory_controller.rb
class FactoryController < ApplicationController
  def index
    @orders = Order.where(is_active: true, exists_in_the_factory: true)
  end

  def print
    @order = Order.find(params[:id])
  end

  def ready
    order = Order.find(params[:id])
    order.update(is_ready_cake: true, ready_cake_time: DateTime.now)
    order.save

    redirect_to factory_path, notice: 'Изменения сохранены!'
  end

  def extradition
    order = Order.find(params[:id])
    order.update(extradition: true, time_of_extradition: DateTime.now, is_active: false)
    order.save

    redirect_to factory_path, notice: 'Отличная работа, Мы сделали доброе дело!'
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index

  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @client_id = User.find(current_user)
    #@orders = Order.where(id_of_app: @client_id)

    if current_user_id == 1
      @orders = Order.where(is_active: true, exists_in_the_store: true)
    else
      @orders = Order.where(is_active: true, exists_in_the_store: true, id_of_app: current_user_id)
    end

  end

  def create
    begin
      json ||= JSON.parse(RestClient.get "http://dc.zekoh.ru/get.php?app=#{current_user_id}")
      puts "тут важно"
      puts json
      if !json.to_s.empty?
        json.each do |data|
          @order = Order.create(id_order: data['id'],
                                name_of_app: data['name_of_app'],
                                id_of_app: data['id_of_app'],
                                date: data['date'],
                                the_theme: data['the_theme'],
                                the_shape: data['the_shape'],
                                price_per_kilogram: data['price_per_kilogram'],
                                weight: data['weight'],
                                difference_in_days_without_days_off: data['difference_in_days_without_days_off'],
                                difference_in_days_with_days_off: data['difference_in_days_with_days_off'],
                                floor: data['floor'],
                                price_for_shape_and_floor: data['price_for_shape_and_floor'],
                                insription: data['insription'],
                                price_for_insription: data['price_for_insription'],
                                name_of_customer: data['name_of_customer'],
                                phone_of_customer: data['phone_of_customer'],
                                there_is_delivery: data['there_is_delivery'],
                                address: data['address'],
                                exists_in_the_store: data['exists_in_the_store'],
                                exists_in_the_factory: data['exists_in_the_factory'],
                                is_ready_cake: data['is_ready_cake'],
                                ready_cake_time: data['ready_cake_time'],
                                is_active: data['is_active'],
                                time_of_creation: data['time_of_creation'])
        end
        redirect_to orders_path
      else
        redirect_to orders_path, notice: 'Новых заявок нет!'
      end
    end

  end

  def cancel
    order = Order.find(params[:id])
    order.update(is_active: false)
    order.save

    redirect_to orders_path, notice: 'Заявка отменена!'
  end

  def pay
    order = Order.find(params[:id])
    order.update( exists_in_the_store: false, exists_in_the_factory: true)
    order.save

    redirect_to orders_path, notice: 'Заявка оплачена и передана в цех!'
  end

  def print
    @order = Order.find(params[:id])
    if @order.there_is_delivery?
      @price_for_delivery = 450
    else
      @price_for_delivery = 0
    end

  end

  def order_params
    params.require(:orders).permit(:name_of_app, :id_of_app, :date, :the_theme, :the_shape, :price_per_kilogram, :weight, :difference_in_days_without_days_off, :difference_in_days_with_days_off, :floor, :price_for_shape_and_floor, :insription, :price_for_insription, :name_of_customer, :phone_of_customer, :there_is_delivery, :address, :exists_in_the_store, :exists_in_the_factory, :is_ready_cake, :ready_cake_time, :is_active)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout 'signin'
  #skip_before_action :user_signed_in?, except: :destroy

  def new
  end

  def create
    user = User.find_by(login: params[:login])
    password = Digest::MD5.hexdigest(params[:password])
    if user && user.password == password
      session[:user_id] = user.id
      case user.role
        when 'admin', 'boss'
          redirect_to statistics_path
        when 'showroom', 'shop'
          redirect_to orders_path
        when 'manufacture'
          redirect_to admin_index_path
        when 'factory'
          redirect_to factory_path
        else
          redirect_to new_session_path, alert: "Проблема с ролью пользователя в системе!"
      end
    else
      redirect_to new_session_path, alert: "Неверный логин или пароль!"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_path, notice: "Сеанс работы завершен!"
  end
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/factory_helper.rb
module FactoryHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/factory/index.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Заказы</a></li>
        <li><a href="#about">Статистика</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><%= current_user.name %></a></li>
        <li> <%= link_to 'выйти', session_url(current_user), method: 'delete' %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container">
  <% if notice %>
      <br/>

      <div class="alert alert-info"> <%= notice %> </div>
  <% end %>
  <% if !@orders.blank? %>
      <table class="table table_toche">
        <caption>

          <form action="/factory">
            <input class="btn btn-warning btn-lg" type="submit" value="ПРОВЕРИТЬ ЗАЯВКИ"/>
          </form>

        </caption>
        <thead>
        <tr>
          <th>№</th>
          <th>Имя</th>
          <th>Телефон</th>
          <th>Цена</th>
          <th>Место продажи</th>
          <th></th>

        </tr>
        </thead>
        <tbody>

        <% @orders.each do |order| %>
            <tr>
              <th scope="row"><%= order.id_order %></th>
              <td><%= order.name_of_customer %></td>
              <td><%= order.phone_of_customer %></td>
              <td>

                <form action="/print_on_factory/<%= order.id %>">
                  <input class="btn btn-primary btn-lg" type="submit" value="НАПЕЧАТАТЬ"/>
                </form>
              </td>
              <td>
                <% if order.is_ready_cake %>
                    <form action="/extradition/<%= order.id %>">
                      <input class="btn btn-success btn-lg" type="submit" value="ТОРТ ВЫДАН КЛИЕНТУ"/>
                    </form>
                <% else %>
                    <form action="/ready/<%= order.id %>">
                      <input class="btn btn-success btn-lg" type="submit" value="ЗАКАЗ ГОТОВ"/>
                    </form>
                <% end %>
              </td>
              <td>
                <%= order.name_of_app %>
              </td>
            </tr>
        <% end %>

        </tbody>
      </table>
  <% else %>
      <caption>Пока тут ничего нет.</caption>
      <br> <br>
      <form action="/factory">
        <input class="btn btn-default btn-lg" type="submit" value="ПРОВЕРИТЬ ЗАЯВКИ"/>
      </form>
  <% end %>
</div> <!-- /container -->
</div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>

app/views/factory/print.html.erb
<script type="text/javascript" charset="utf-8">
    $(document).ready(function () {
        window.print();
        window.close();

      /*var win = window.open();
       self.focus();
       win.document.open();
       win.document.write('<'+'html'+'><'+'body'+'>');
       win.document.write(printThis);
       win.document.write('<'+'/body'+'><'+'/html'+'>');
       win.document.close();
       win.print();
       win.close(); */
    });
</script>
<div class="container print">
  <div class="logo_container">
    <%= image_tag "logo.png", id: 'logo' %>
  </div>
  <br>
  <br>
  <form action="/factory">
    <input class="btn btn-primary btn-lg" type="submit" value="Заказ № <%= @order.id_order %>"/>
  </form>
  <br>

  <br>
  <table class="table">
    <thead>
    <tr>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tbody>

    <tr>
      <th><b>Имя:</b></th>
      <td><%= @order.name_of_customer %></td>
    </tr>
    <tr>
      <th>Телефон:</th>
      <td><%= @order.phone_of_customer %></td>
    </tr>
    <tr>
      <th>Дата выдачи:</th>
      <td><%= @order.date %></td>
    </tr>
    <tr>
      <th>Тема украшения:</th>
      <td><%= @order.the_theme %></td>
    </tr>
    <% if @order.insription.length > 0 %>
        <tr>
          <th>Надпись на табличке:</th>
          <td><%= @order.insription %></td>
        </tr>
    <% else %>
        <tr>
          <th>Надпись на табличке:</th>
          <td>Без поздравительной надписи</td>
        </tr>
    <% end %>

    <tr>
      <th>Форма:</th>
      <td><%= @order.the_shape %></td>
    </tr>
    <tr>
      <th>Кол-во ярусов:</th>
      <td><%= @order.floor %></td>
    </tr>
    <tr>
      <th>Вес:</th>
      <td><%= @order.weight %></td>
    </tr>
    <% if @order.address.length > 0 %>
        <tr>
          <th>Адресс доставки:</th>
          <td><%= @order.address %></td>
        </tr>
    <% else %>
        <tr>
          <th>Доставка:</th>
          <td>Без доставки</td>
        </tr>
    <% end %>
    <tr>
      <th>Цена:</th>
      <td><%= @order.price_for_shape_and_floor %> руб.</td>
    </tr>
    </tbody>
  </table>


  <% if @order.address.length > 0 %>

  <% else %>
      <b>Самовывоз производится по адресу: г.Майкоп, Хлебокомбинат, ул. Привокзальная 128</b><br> <br>
  <% end %>
  <b>ShowRoom Жак-Андрэ:</b><br>
  <b>г.Майкоп, Хлебокомбинат, ул. Привокзальная 128</b> <br>
  тел.: +7(928)467-87-81 <br>
  instagram.com/jacques_andre_ <br>
  <br>
  <b>Магазин Жак-Андрэ:</b> <br>
  <b>г.Майкоп, ул. Первомайская 193</b> <br>
  тел.: +7(900)246-20-50 <br>
  instagram.com/jacques_andre_ <br><br>
  <div class="rules">
    *Подписывая Вы соглашаетесь с условиями заказа торта.
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Digital Cake</title>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href=<%= asset_path 'bootstrap.min.css'%>>
    <link href=<%= asset_path 'fixed-top-bar.css' %> rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <script src=<%= asset_path 'inputmask.js'%>></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/signin.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Digital Cake</title>

  <link rel="stylesheet" href=<%= asset_path 'bootstrap.min.css'%>>
  <link href=<%= asset_path 'signin.css' %> rel="stylesheet">
</head>

<body>
<%= yield %>
</body>
</html>

app/views/orders/index.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Заказы</a></li>
        <li><a href="#about">Статистика</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><%= current_user.name %></a></li>
        <li> <%= link_to 'выйти', session_url(current_user), method: 'delete' %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container">
  <% if notice %>
      <br/>

      <div class="alert alert-info"> <%= notice %> </div>
  <% end %>
  <% if !@orders.blank? %>
  <table class="table table_toche">
    <caption>
<button type="button" class="btn btn-default btn-lg">ПЕРЕДАТЬ В ЦЕХ</button>
      <br> <br>
      <form action="/get">
        <input class="btn btn-warning btn-lg" type="submit" value="ПРОВЕРИТЬ ЗАЯВКИ" />
      </form>

    </caption>
    <thead>
    <tr>
      <th>№</th>
      <th>Имя</th>
      <th>Телефон</th>
      <th>Цена</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tbody>

    <% @orders.each do |order| %>
    <tr>
      <th scope="row"><%= order.id_order %></th>
      <td><%= order.name_of_customer %></td>
      <td><%= order.phone_of_customer %></td>
      <td>

        <form action="/print/<%= order.id %>">
          <input class="btn btn-primary btn-lg" type="submit" value="НАПЕЧАТАТЬ" />
        </form>
      </td>
      <td>
        <form action="/pay/<%= order.id %>">
          <input class="btn btn-success btn-lg" type="submit" value="ОПЛАТИЛ" />
        </form>
      </td>
      <td>
        <form action="/cancel/<%= order.id %>">
          <input class="btn btn-danger btn-lg" type="submit" value="ОТМЕНА" />
        </form>
      </td>
    </tr>
    <% end %>

    </tbody>
  </table>
<% else %>
      <caption>Пока тут ничего нет.</caption>
      <br> <br>
      <form action="/get">
        <input class="btn btn-default btn-lg" type="submit" value="ПРОВЕРИТЬ ЗАЯВКИ" />
      </form>
  <% end %>
</div> <!-- /container -->
</div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>

app/views/orders/print.html.erb
<script type="text/javascript" charset="utf-8">
    $(document).ready(function () {
        window.print();
        //window.close();

      /*var win = window.open();
       self.focus();
       win.document.open();
       win.document.write('<'+'html'+'><'+'body'+'>');
       win.document.write(printThis);
       win.document.write('<'+'/body'+'><'+'/html'+'>');
       win.document.close();
       win.print();
       win.close(); */
    });
</script>
<div class="container print">
  <div class="logo_container">
    <%= image_tag "logo.png", id: 'logo' %>
  </div>
  <br>
  <br>
  <form action="/orders">
    <input class="btn btn-primary btn-lg" type="submit" value="Заказ № <%= @order.id_order %>"/>
  </form>
  <br>

  <br>
  <table class="table">
    <thead>
    <tr>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tbody>

    <tr>
      <th><b>Имя:</b></th>
      <td><%= @order.name_of_customer %></td>
    </tr>
    <tr>
      <th>Телефон:</th>
      <td><%= @order.phone_of_customer %></td>
    </tr>
    <tr>
      <th>Дата выдачи:</th>
      <td><%= @order.date %></td>
    </tr>
    <tr>
      <th>Тема украшения:</th>
      <td><%= @order.the_theme %></td>
    </tr>
    <% if @order.insription.length > 0 %>
        <tr>
          <th>Надпись на табличке:</th>
          <td><%= @order.insription %></td>
        </tr>
    <% else %>
        <tr>
          <th>Надпись на табличке:</th>
          <td>Без поздравительной надписи</td>
        </tr>
    <% end %>

    <tr>
      <th>Форма:</th>
      <td><%= @order.the_shape %></td>
    </tr>
    <tr>
      <th>Кол-во ярусов:</th>
      <td><%= @order.floor %></td>
    </tr>
    <tr>
      <th>Вес:</th>
      <td><%= @order.weight %></td>
    </tr>
    <% if @order.address.length > 0 %>
        <tr>
          <th>Адресс доставки:</th>
          <td><%= @order.address %></td>
        </tr>
    <% else %>
        <tr>
          <th>Доставка:</th>
          <td>Без доставки</td>
        </tr>
    <% end %>
    <tr>
      <th>Цена:</th>
      <td><%= @order.price_for_shape_and_floor.to_i + @order.price_for_insription.to_i + @price_for_delivery + 200%> руб.</td>
    </tr>
    </tbody>
  </table>

  <div class="signature">
    Дата заказа: <%= Date.today %> _________________________________ <br>
    подпись &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  </div>

  <% if @order.address.length > 0 %>

  <% else %>
      <b>Самовывоз производится по адресу: г.Майкоп, Хлебокомбинат, ул. Привокзальная 128</b><br> <br>
  <% end %>
  <b>ShowRoom Жак-Андрэ:</b><br>
  <b>г.Майкоп, Хлебокомбинат, ул. Привокзальная 128</b> <br>
  тел.: +7(928)467-87-81 <br>
  instagram.com/jacques_andre_ <br>
  <br>
  <b>Магазин Жак-Андрэ:</b> <br>
  <b>г.Майкоп, ул. Первомайская 193</b> <br>
  тел.: +7(900)246-20-50 <br>
  instagram.com/jacques_andre_ <br><br>
  <div class="rules">
    *Подписывая Вы соглашаетесь с условиями заказа торта.
  </div>
</div>

app/views/orders/web.html.erb
<!-- Стили datepicker -->
<link href=<%= asset_path 'jquery-ui.min.css' %> rel="stylesheet">
<script src=<%= asset_path 'inputmask.js' %>></script>

<script src=<%= asset_path 'jquery-ui.min.js' %>></script>

<script type="text/javascript" charset="utf-8">
    $.datepicker.regional['ru'] = {
        closeText: 'Закрыть',
        prevText: '&#x3c;Пред',
        nextText: 'След&#x3e;',
        currentText: 'Сегодня',
        monthNames: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь',
            'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
        monthNamesShort: ['Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн',
            'Июл', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек'],
        dayNames: ['воскресенье', 'понедельник', 'вторник', 'среда', 'четверг', 'пятница', 'суббота'],
        dayNamesShort: ['вск', 'пнд', 'втр', 'срд', 'чтв', 'птн', 'сбт'],
        dayNamesMin: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
        dateFormat: 'dd.mm.yy',
        firstDay: 1,
        isRTL: false
    };
    $.datepicker.setDefaults($.datepicker.regional['ru']);
    $(document).ready(function () {
        //$('#datepicker').setDefaults( $.datepicker.regional[ "ru" ] );
//        $.datepicker.defaults = {regional:"ru"};
        $("#datepicker").datepicker();


    });
</script>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Заказы</a></li>
        <li><a href="#about">Статистика</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><%= current_user.name %></a></li>
        <li> <%= link_to 'выйти', session_url(current_user), method: 'delete' %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container center">
  <h4>Выбирите дату, когда торт должен быть готов:</h4>
  <br>
  <div class="col-md-12 center">
    <div id="datepicker" class="datepicker">
    </div>
    <br> <br> <br>
  </div>

  <h4>Выбирите тему украшения:</h4>
  <br>
  <div class="col-md-6">
    <div class="img_theme">
      <%= image_tag "anniversary.jpg", id: 'theme-wedding' %>
    </div>

    <br>
    <h5>Выбирите тему украшения:</h5>
  </div>


  <div class="col-md-6">
    <div class="img_theme">
      <%= image_tag "bithday.jpg", id: 'theme-wedding' %>
    </div>

    <br>
    <h5>Выбирите тему украшения:</h5>
  </div>
  <div class="col-md-6">
    <div class="img_theme">
      <%= image_tag "child.jpg", id: 'theme-wedding' %>
    </div>

    <br>
    <h5>Выбирите тему украшения:</h5>
  </div>
  <div class="col-md-6">
    <div class="img_theme">
    <%= image_tag "wedding.jpg", id: 'theme-wedding' %>
    </div>
    <br>
    <h5>Выбирите тему украшения:</h5>
  </div>
  <div class="col-md-12">
    <h5>Надпись на табличке:</h5>
    <input type="text" placeholder="">
  </div>
  <div class="col-md-12">
    <h5>Имя клиента:</h5>
    <input type="text" placeholder="">
  </div>
  <div class="col-md-12">
    <h5>Телефон:</h5>
    <input type="text" placeholder="">
  </div>
  <div class="col-md-12">
    <h5>Доставка:</h5>
    <input type="text" placeholder="">
  </div>


</div> <!-- /container -->
</div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->

app/views/statistics/index.html.erb
<li><a href="#"><%= current_user.name %></a></li>
<li> <%= link_to 'выйти', session_url(current_user), method: 'delete' %></li>